// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

declare module "*.svg?raw" {
  const content: string;
  export default content;
}

// API Response types
type APIResponse<T = unknown> = {
  success: boolean;
  data?: T;
  error?: string;
};

type APIResult = {
  success: boolean;
  error?: string;
};

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}

interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface SettingsAPI {
  getCurrentSchoolYear: () => Promise<string>;
  setCurrentSchoolYear: (schoolYear: string) => Promise<void>;
  getGlobalBlockedWeeks: () => Promise<
    import("./services/curriculum-database").BlockedWeek[]
  >;
  setGlobalBlockedWeeks: (
    blockedWeeks: import("./services/curriculum-database").BlockedWeek[],
  ) => Promise<void>;
}

interface MagisterAPI {
  authenticate: () => Promise<APIResponse>;
  getTodayInfo: () => Promise<APIResponse>;
  getUserInfo: () => Promise<APIResponse>;
  logout: () => Promise<APIResult>;
  isAuthenticated: () => Promise<APIResponse<boolean>>;
  testAPI: () => Promise<APIResponse>;
  getAllStudents: () => Promise<
    APIResponse<{ items: import("./services/student-database").Student[] }>
  >;
  clearToken: () => Promise<APIResult>;
  fetchStudentPhoto: (studentId: number) => Promise<APIResponse<string>>;
}

interface StudentDBAPI {
  saveStudents: (
    students: import("./services/student-database").Student[],
  ) => Promise<APIResult>;
  getAllStudents: () => Promise<
    APIResponse<import("./services/student-database").Student[]>
  >;
  searchStudents: (
    query: string,
  ) => Promise<APIResponse<import("./services/student-database").Student[]>>;
  getMetadata: () => Promise<
    APIResponse<{
      key: string;
      value: string;
      totalCount: number;
    }>
  >;
  clearAllData: () => Promise<APIResult>;
  savePhoto: (externeId: string, photoData: string) => Promise<APIResult>;
  getPhoto: (externeId: string) => Promise<APIResponse<string | null>>;
}

interface CurriculumAPI {
  getAllPlans: () => Promise<
    APIResponse<{
      plans: import("./services/curriculum-database").CurriculumPlan[];
    }>
  >;
  getPlanByClass: (
    className: string,
  ) => Promise<
    APIResponse<import("./services/curriculum-database").CurriculumPlan>
  >;
  savePlan: (
    plan: import("./services/curriculum-database").CurriculumPlan,
  ) => Promise<APIResult>;
  deletePlan: (planId: string) => Promise<APIResult>;
  exportPlanToDocx: (
    planId: string,
    language: "nl" | "en",
    className?: string,
  ) => Promise<APIResponse<string>>;
}

interface TestAPI {
  getAllTests: () => Promise<
    APIResponse<import("./services/test-database").Test[]>
  >;
  getTestsForClassGroup: (
    classGroup: string,
  ) => Promise<APIResponse<import("./services/test-database").Test[]>>;
  getTest: (
    testId: string,
  ) => Promise<APIResponse<import("./services/test-database").Test>>;
  createTest: (
    test: Omit<
      import("./services/test-database").Test,
      "id" | "createdAt" | "updatedAt"
    >,
  ) => Promise<APIResponse<import("./services/test-database").Test>>;
  updateTest: (
    testId: string,
    updates: Partial<import("./services/test-database").Test>,
  ) => Promise<APIResponse<import("./services/test-database").Test>>;
  deleteTest: (testId: string) => Promise<APIResult>;
  getGradesForTest: (
    testId: string,
  ) => Promise<APIResponse<import("./services/test-database").StudentGrade[]>>;
  getGradesForStudent: (
    studentId: number,
    classGroup: string,
  ) => Promise<APIResponse<import("./services/test-database").StudentGrade[]>>;
  saveGrade: (
    testId: string,
    studentId: number,
    pointsEarned: number,
    manualOverride?: number,
  ) => Promise<APIResponse<import("./services/test-database").StudentGrade>>;
  saveCompositeGrade: (
    testId: string,
    studentId: number,
    elementGrades: import("./services/test-database").CompositeElementGrade[],
    manualOverride?: number,
  ) => Promise<APIResponse<import("./services/test-database").StudentGrade>>;
  getTestStatistics: (
    testId: string,
    classGroup?: string,
  ) => Promise<APIResponse<import("./services/test-database").TestStatistics>>;
}

interface ExamnetAPI {
  login: (username: string, password: string) => Promise<APIResponse>;
  logout: () => Promise<APIResult>;
  getTests: () => Promise<APIResponse>;
  getTestResults: (testId: string) => Promise<APIResponse>;
  getStudents: () => Promise<APIResponse>;
  syncData: () => Promise<APIResponse>;
}

declare interface Window {
  themeMode: ThemeModeContext;
  themeGlobal: {
    get: () => Promise<
      | "system"
      | "twitter"
      | "graphite"
      | "nord"
      | "dracula"
      | "solarized"
      | undefined
    >;
    set: (
      theme:
        | "system"
        | "twitter"
        | "graphite"
        | "nord"
        | "dracula"
        | "solarized",
    ) => Promise<boolean>;
  };
  electronWindow: ElectronWindow;
  settingsAPI: SettingsAPI;
  magisterAPI: MagisterAPI;
  studentDBAPI: StudentDBAPI;
  curriculumAPI: CurriculumAPI;
  testAPI: TestAPI;
  examnetAPI: ExamnetAPI;
}
